<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array|\AppendIterator $values
 * @var array $templateProperties
 */

// Wrap the core template view/common/resource-values with group labels, if any.

// This path should be updated to override it.
$mainViewTemplate = OMEKA_PATH . '/application/view/common/resource-values.phtml';

// When the module AdvancedResourceTemplate is not available, use default template.
// Normally useless, except when copied in a theme.
if (!$values || !class_exists('AdvancedResourceTemplate\Api\Representation\ResourceTemplatePropertyDataRepresentation')) {
    include $mainViewTemplate;
    return;
}

$plugins = $this->getHelperPluginManager();

/*
// Can be used to optimize the included main view template when not using the core one.
if ($this->status()->isSiteRequest()) {
    $siteSetting = $plugins->get('siteSetting');
    $labelInfo = $siteSetting('property_label_information');
    $showLocale = (bool) $siteSetting('show_locale_label', true);
    $filterLocale = (bool) $siteSetting('filter_locale_values');
    $lang = $plugins->get('lang')();
    $showValueAnnotations = (bool) $siteSetting('show_value_annotations', false);
} else {
    $setting = $plugins->get('setting');
    $labelInfo = $setting('property_label_information');
    $showLocale = true;
    $filterLocale = false;
    $lang = null;
    $showValueAnnotations = true;
}
*/

// For compatibility with value annotations, waiting fix omeka/omeka-s#1997.
if (empty($resource)) {
    /** @var \Omeka\Api\Representation\ValueRepresentation $firstValueValue */
    $firstValue = is_array($values) ? reset($values) : $values->current();
    $firstValueValue = reset($firstValue['values']);
    $resource = $firstValueValue->resource();
}
$templateProperties ??= [];

/**
 * @var \AdvancedResourceTemplate\Api\Representation\ResourceTemplateRepresentation $template
 * @var array $groups
 */
$template = $resource->resourceTemplate();
$groups = $template ? $template->dataValue('groups', []) : null;

if (!$template || !$groups) {
    include $mainViewTemplate;
    return;
}

$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
?>

<div class="property-groups">
    <?php
    // $values is an AppendIterator: array_filter(), count(), etc. cannot be used.
    $sourceValues = $values;
    foreach (array_keys($groups) as $groupLabel):
        $valuesGroup = new \AppendIterator();
        $sourceValuesFiltered = new \AppendIterator();
        foreach ($sourceValues as $term => $propertyData) {
            $propertyData['group'] === $groupLabel
                ? $valuesGroup->append(new \ArrayIterator([$term => $propertyData]))
                : $sourceValuesFiltered->append(new \ArrayIterator([$term => $propertyData]));
        }
        $sourceValues = $sourceValuesFiltered;
        if ($valuesGroup->key() !== null):
            $values = $valuesGroup;
        ?>
    <div class="property-group">
        <h3><?= $escape($groupLabel) ?></h3>
        <?php include $mainViewTemplate; ?>
    </div>
        <?php endif;
    endforeach;
    // Display metadata that are not in any group.
    if ($sourceValues->key()):
        $values = $sourceValues; ?>
    <div class="property-group">
        <h3><?= $escape($translate('Other metadata')) ?></h3>
        <?php include $mainViewTemplate; ?>
    </div>
    <?php endif; ?>
</div>
