<footer class="mt-auto text-white-50">
    <p> Design by 
    <a target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
            <img style="height: 40px;" src="<?php echo $this->assetUrl('img/logo_paragraphe_blanc.png'); ?>" alt="Laboratoire Paragraphe" />
    <a href="https://samszo.univ-paris8.fr/" >Samuel Szoniecky</a>
    <a href="https://gabariellegg.github.io/cvA2020/" >Gabrielle Godin</a>
    </p>            
</footer>
