<?php
$userBar = $this->userBar();

?>
<header class="fondBloc mb-auto">


    <nav class="navbar navbar-expand-lg navbar-dark bg-black">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                <h3>Feuillet numérique - Enquête</h3>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="container">
                    <div class="row">
                        <div class="col" style="text-align: left;">
                            <h3>Feuillet numérique - Enquête</h3>
                            <h6>Médiation numérique et éditorialisation des institutions théâtrales</h6>
                        </div>
                        <div class="col" style="text-align: end;">
                            <a target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
                                <img style="height:34px;"
                                    src="<?php echo $this->assetUrl('img/logo_paragraphe_blanc.png'); ?>"
                                    alt="Laboratoire Paragraphe" />
                            </a>
                            <a target="_blank" href="https://www.univ-paris8.fr/">
                                <img style="height:34px;" src="<?php echo $this->assetUrl('img/logop8.jpg'); ?>"
                                    alt="Université Paris 8" />
                            </a>
                            <a target="_blank" href="https://www.ulaval.ca/">
                                <img style="height:34px;"
                                    src="<?php echo $this->assetUrl('img/logo-ulaval-reseaux-sociaux.jpg'); ?>"
                                    alt="Université Laval" />
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-9" style="text-align: left;">
                            <ul class="list-unstyled">
                                <li> - Un projet de recherche doctoral de Gabrielle Godin (U. Laval et U. Paris 8)</li>
                                <li> - Dirigé par Renée Bourassa (U. Laval), Imad Saleh (U. Paris 8) et co-dirigé par
                                    Samuel
                                    Szoniecky (U. Paris 8)</li>
                            </ul>
                        </div>
                        <div class="col-3 text-end">
                            <?php echo $userBar;?>
                        </div>
                    </div>
                <div class="row">
                    <div class="d-flex align-items-center bd-highlight justify-content-center bg-dark"
                        style="height:6em">
                        <h2>Evaluer le pouvoir d'agir par des cribles</h2>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </nav>
</header>