<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $resourceTemplate
 */

// Copy of original file + resource template data and resource template properties data + export csv/tsv.

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$url = $this->plugin('url');

$this->headLink()->appendStylesheet($this->assetUrl('css/advanced-resource-template-admin.css', 'AdvancedResourceTemplate'));
$this->htmlElement('body')->appendAttribute('class', 'resource-templates show');
?>

<?php echo $this->pageTitle($resourceTemplate->label(), 1, $translate('Resource templates')); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="button expand" aria-label="<?= $translate('Expand') ?>" title="<?= $translate('Expand') ?>">
            <?= $translate('Export') ?></a>
            <ul class="collapsible">
                <li><a class="link" href="<?= $escape($url(null, ['action' => 'export'], ['query' => ['output' => 'csv']], true)) ?>"><?= $translate('As csv') ?></a></li>
                <li><a class="link" href="<?= $escape($url(null, ['action' => 'export'], ['query' => ['output' => 'tsv']], true)) ?>"><?= $translate('As tsv') ?></a></li>
                <li><a class="link" href="<?= $escape($url(null, ['action' => 'export'], ['query' => ['output' => 'json']], true)) ?>"><?= $translate('As json') ?></a></li>
            </ul>
    </div>
    <?php if ($resourceTemplate->userIsAllowed('update')): ?>
    <a class="button" href="<?= $escape($resourceTemplate->url('edit')) ?>"><?= $translate('Edit') ?></a>
    <?php endif; ?>
</div>

<?php if ($resourceTemplate->resourceClass()): ?>
<div class="class-row">
    <span class="class-label"><?php echo $translate('Class'); ?></span>
    <span class="class-value"><?php echo $translate($resourceTemplate->resourceClass()->label()); ?></span>
    <span class="class-term"><?php echo $translate($resourceTemplate->resourceClass()->term()); ?></span>
</div>
<?php endif; ?>

<table id="properties" class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
    <tr>
        <th><?php echo $translate('Original label'); ?></th>
        <th><?php echo $translate('Data types'); ?></th>
        <th><?php echo $translate('Alternate label'); ?></th>
        <th><?php echo $translate('Alternate comment'); ?></th>
        <th><?php echo $translate('Required?'); ?></th>
        <th><?php echo $translate('Private?'); ?></th>
        <th><?php echo $translate('Other settings'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($resourceTemplate->resourceTemplateProperties() as $resourceTemplateProperty) foreach ($resourceTemplateProperty->data() ?: [$resourceTemplateProperty] as $rtpData): ?>
        <?php $property = $resourceTemplateProperty->property(); ?>
        <?php $resourceTemplateProperty = $rtpData; ?>
        <tr data-property-id="<?php echo $escape($property->id()); ?>">
            <td>
                <span>
                    <span class="property-label"><?php echo $escape($translate($property->label())); ?></span>
                    <span class="property-term"><?php echo $escape($translate($property->term())); ?></span>
                </span>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $property->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td>
                <ul>
                    <?php foreach ($resourceTemplateProperty->dataTypeLabels() as $dataTypeLabel): ?>
                    <li><?php echo $escape($dataTypeLabel['label']); ?></li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td><?php echo $escape($resourceTemplateProperty->alternateLabel()); ?></td>
            <td><?php echo $escape($resourceTemplateProperty->alternateComment()); ?></td>
            <td><?php echo $resourceTemplateProperty->isRequired() ? $translate('Yes') : $translate('No'); ?></td>
            <td><?php echo $resourceTemplateProperty->isPrivate() ? $translate('Yes') : $translate('No'); ?></td>
            <td><dl><?php foreach ($resourceTemplateProperty->data() as $key => $value): ?>
                <?php if (!$value || mb_substr($key, 0, 2) === 'o:' || in_array($key, ['is-title-property', 'is-description-property'])) continue; ?>
                <dt><?php echo str_replace('_', ' ', $key); ?></dt>
                <?php if (is_array($value)): ?>
                    <?php foreach ($value as $k => $v): ?>
                        <?php if (is_array($v)) $v = json_encode($v, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT); ?>
                <dd><?php echo $escape((is_numeric($k) ? '' : $k . ' = ') . $v); ?></dd>
                    <?php endforeach; ?>
                <?php else: ?>
                <dd><?php echo $escape($value); ?></dd>
                <?php endif; ?>
            <?php endforeach;
            ?></dl></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php if (array_filter($resourceTemplate->data())): ?>
<hr style="margin-top: 24px; opacity: 0.1;">
<div>
    <span class="label" style="font-weight: bold;"><?php echo $translate('Advanced settings'); ?></span>
    <dl><?php foreach ($resourceTemplate->data() as $key => $value): ?>
        <?php if (!$value) continue; ?>
        <dt><?php echo str_replace('_', ' ', $key); ?></dt>
        <?php if (is_array($value)): ?>
            <?php foreach ($value as $k => $v): ?>
                <?php if (is_array($v)) $v = json_encode($v, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT); ?>
        <dd><?php echo $escape((is_numeric($k) ? '' : $k . ' = ') . $v); ?></dd>
            <?php endforeach; ?>
        <?php else: ?>
        <dd><?php echo $escape($value); ?></dd>
        <?php endif; ?>
        <?php endforeach;
    ?></dl>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
