<?php
$translate = $this->plugin('translate');
$this->headStyle()->appendStyle('
.lockout-log th {
    font-weight: bold;
}
.lockout-log td,
.lockout-log th {
    padding: 1px 5px 1px 5px;
}
td.lockout-ip {
    font-family:  "Courier New", Courier, monospace;
    vertical-align: top;
}
td.lockout-max {
    width: 100%;
}
');
$form->prepare();
?>
<h3><?php echo $translate('Statistics'); ?></h3>

<p><?php
$activeLockouts = count($lockouts);
if (empty($activeLockouts)):
    echo $translate('No active lockout.');
else:
    echo sprintf($this->translatePlural(
        '%d IP is currently blocked from trying to log in.',
        '%d IPs are currently blocked from trying to log in.',
        $activeLockouts), $activeLockouts);
    echo $this->formRow($form->get('lockout_clear_current_lockouts'));
endif;
?></p>

<p><?php
if (empty($lockout_total)):
    echo $translate('No lockouts yet.');
else:
    echo sprintf($this->translatePlural(
        '%d lockout since last reset.',
        '%d lockouts since last reset.',
        $lockout_total), $lockout_total);
    echo $this->formRow($form->get('lockout_clear_total_lockouts'));
endif;
?></p>

<h3><?php echo $translate('Options'); ?></h3>
<h4><?php echo $translate('Lockout'); ?></h4>
<?php echo $this->formRow($form->get('lockout_allowed_retries')); ?>
<?php echo $this->formRow($form->get('lockout_lockout_duration')); ?>
<?php echo $this->formRow($form->get('lockout_allowed_lockouts')); ?>
<?php echo $this->formRow($form->get('lockout_long_duration')); ?>
<?php echo $this->formRow($form->get('lockout_valid_duration')); ?>
<?php echo $this->formRow($form->get('lockout_whitelist')); ?>

<h4><?php echo $translate('Site connection'); ?></h4>
<?php echo $client_type_message; ?>
<?php echo $this->formRow($form->get('lockout_client_type')); ?>
<?php if ($client_type_warning): ?>
<p>
<strong><?php echo $translate('Current setting appears to be invalid.'); ?></strong>
<?php echo $translate('Please make sure it is correct.'); ?>
<?php echo sprintf(
    $translate('Further information can be found <a href="%s" title="README">here</a>.'),
    'https://gitlab.com/Daniel-KM/Omeka-S-module-Lockout'); ?>
<?php endif; ?>
<?php // echo $this->formRow($form->get('lockout_cookies')); ?>

<h4><?php echo $translate('Notification'); ?></h4>
<?php echo $this->formRow($form->get('lockout_lockout_notify')); ?>
<?php echo $this->formRow($form->get('lockout_notify_email_after')); ?>

<h3><?php echo $translate('Lockout log'); ?></h3>
<?php if (empty($logs)): ?>
<p><?php echo $translate('No log currently.'); ?></p>
<?php else:
echo $this->formRow($form->get('lockout_clear_logs')); ?>
<div class="lockout-log">
    <table class="form-table">
        <thead>
            <tr>
                <th scope="col"><?php echo $translate('IP'); ?></th>
                <th scope="col"><?php echo $translate('Tried to log in as'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($logs as $ip => $arr): ?>
            <tr>
                <td class="lockout-ip"><?php echo $ip; ?></td>
                <td class="lockout-max">
                <?php $next = false;
                foreach ($arr as $user => $count):
                    if ($next):
                        echo ', ';
                    else:
                        $next = true;
                    endif;
                    echo $user . ' (' . sprintf($this->translatePlural('%d lockout', '%d lockouts', $count), $count) . ')';
                endforeach;
                ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>
