<?php
$institution = $project->value('mare:originatingInstitution');
if ($institution && $institution->valueResource()) {
    $institution = $institution->valueResource();
}
$summary = $project->value('mare:summary');
$collectingUrl = $project->value('mare:collectingUrl');
$collectionUrl = $project->value('mare:collectionUrl');
// Set the logo.
$logo = $this->thumbnail($project, 'medium');
if (!$logo && $institution) {
    // There is no project logo. Use the institution logo.
    $logo = $this->thumbnail($institution, 'medium');
}
if (!$logo) {
    // There is no logo. Insert a placeholder image.
    $logo = '';
}
?>

<div class="project">
    <div class="logo">
        <?php echo $logo; ?>
    </div>
    <div class="project-meta">
        <h3 class="title"><?php echo $this->escapeHtml($project->displayTitle()); ?></h3>
        <p class="institution"><?php echo $institution ? $institution->displayTitle() : ''; ?></p>
        <?php if ($summary): ?>
        <p class="description"><?php echo $this->escapeHtml($summary); ?></p>
        <?php endif; ?>
        <div class="links">
          <?php echo sprintf(
              '%s | %s | %s',
              $collectingUrl ? $this->hyperlink('Contribute', $collectingUrl->uri(), ['class' => 'o-icon-external contribute-link']) : 'Contribute',
              $collectionUrl ? $this->hyperlink('View Collection', $collectionUrl->uri(), [
                  'class' => 'o-icon-external view-collection-link',
                  'target' => '_blank',
                  'aria-label' => 'External Link',
              ]) : 'View Collection',
              $this->hyperlink('Project info', $project->siteUrl(), ['class' => 'project-info-link']),
              //$institution ? ' | ' . $this->hyperlink('Institution info', $institution->siteUrl(), ['class' => 'institution-link']) : ''
          ); ?>
        </div>
    </div>
</div>
