<?php if ($projects): ?>

<div class="results-copy">
    <?php echo sprintf(
        '%s collecting %s your criteria',
        count($projects),
        (1 === count($projects)) ? 'project meets' : 'projects meet'
    ); ?>
</div>
<?php foreach ($projects as $project):  ?>
<?php echo $this->partial('project.phtml', ['project' => $project]); ?>
<?php endforeach; ?>

<?php else: ?>

<p>No collecting projects meet your criteria. To find a collecting project, try
choosing only the criteria which are most important to you. Or you can try one
of these projects, which are collecting widely, if there is not a project more
specific to your contributions.</p>
<?php foreach ($projectsPriority as $project):  ?>
<?php echo $this->partial('project.phtml', ['project' => $project]); ?>
<?php endforeach; ?>

<?php endif; ?>
