<?php
$translate = $this->plugin('translate');
?>
<nav aria-label="<?php echo $translate('Pagination'); ?>" class="input-group pagination">
<?php if ($totalCount): ?>
        <form method="GET" action="" class="input-group">
            <?php echo $this->queryToHiddenInputs(['page']); ?>
            <input type="text" name="page" class="page-input-top input-group-field" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
            <span class="page-count input-group-label"><?php echo sprintf($translate('of %s'), $pageCount); ?></span>
        </form>

      <div class="input-group-button">
      <?php if ($currentPage != 1): ?>
      <?php echo $this->hyperlink('', $previousPageUrl, ['title' => $translate('Previous'), 'aria-label' => $translate('Previous'), 'class' => 'pagination-previous o-icon-prev button']); ?>
      <?php else: ?>
      <span class="pagination-previous o-icon-prev button disabled"></span>
      <?php endif; ?>
      </div>
  
      <div class="input-group-button">
      <?php if ($currentPage < $pageCount): ?>
      <?php echo $this->hyperlink('', $nextPageUrl, ['title' => $translate('Next'), 'aria-label' => $translate('Next'), 'class' => 'pagination-next o-icon-next button']); ?>
      <?php else: ?>
      <span class="pagination-next o-icon-next button inactive"></span>
      <?php endif; ?>
      </div>
  
      <?php
      $from = $offset + 1;
      $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
      ?>
      <div class="input-group-label">
        <span class="row-count"><?php echo sprintf($translate('%s–%s of %s'), $from, $to, $totalCount); ?></span>
      </div>
<?php else: ?>
    <?php echo $translate('0 results'); ?>
<?php endif; ?>
</nav>
