<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form" class="input-group">
    <input type="text" name="search" value="<?php echo $searchValue; ?>" placeholder="<?php echo 'Search the archive'; ?>" class="input-group-field">
    <div class="input-group-button">
        <button type="submit" class="primary button"><?php echo $translate('Search'); ?></button>
    </div>
</form>
