<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $results
 * @var array $totals
 * @var string $type "value"
 * @var string[] $resourceTypes
 * @var int[]|null $periods
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 * @var string $propertyFilter
 * @var string $valueTypeFilter
 * @var string $byPeriodFilter
 * @var string $compute
 * @var bool $hasAdvancedSearch
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$isAdminRequest = $this->status()->isAdminRequest();
$query = $this->params()->fromQuery();

$currentUrl = $urlHelper(null, [], true);

$isMetadata = in_array($valueTypeFilter, ['resource_class', 'resource_template', 'owner']);
$isSimpleValue = !in_array($valueTypeFilter, ['resource', 'uri' , 'resource_class', 'resource_template', 'owner']);
$isResource = $valueTypeFilter === 'resource';
$isUri = $valueTypeFilter === 'uri';
$isResourceClass = $valueTypeFilter === 'resource_class';
$isResourceTemplate = $valueTypeFilter === 'resource_template';
$isOwner = $valueTypeFilter === 'owner';
$isLinked = $isResource || $isResourceClass || $isResourceTemplate || $isOwner;
$isByAll = !in_array($byPeriodFilter, ['year', 'month']);
$isByCount = !in_array($compute, ['percent', 'evolution', 'variation']);

$isAllPeriods = $byPeriodFilter === 'all';
$isYearPeriods = $byPeriodFilter === 'year';
// $hasResults = !empty($results) && ($isAllPeriods ? !empty($results['all']) : true);
?>

<?= $this->pageTitle($translate('By value'), 1, $isAdminRequest ? $translate('Statistics') : null) ?>

<?= $this->partial('common/statistics-nav') ?>

<form method="get">
<div class="flex-container">
    <div>
        <?php foreach (['resources' => $translate('Resources'), 'item_sets' => $translate('Item sets'), 'items' => $translate('Items'), 'media' => $translate('Medias')] as $resourceType => $label): ?>
        <label><input type="checkbox" name="resource_type[]" id="resource_type_resources" value="<?= $resourceType ?>"<?= in_array($resourceType, $resourceTypes) ? ' checked="checked"' : '' ?>><?= $label ?></label>
        <?php endforeach; ?>
    </div>

    <?= $this->propertySelect([
        'name' => 'property',
        'options' => [
            'empty_option' => $translate('Select a property'),
            'term_as_value' => true,
            'used_terms' => true,
        ],
        'attributes' => [
            'class' => 'chosen-select',
            'required' => false,
            'value' => $propertyFilter,
        ],
    ]) ?>

    <div>
        <label><input type="radio" name="value_type" value="value"<?= $isSimpleValue ? ' checked="checked"' : '' ?>><?= $translate('Value') ?></label>
        <label><input type="radio" name="value_type" value="resource"<?= $valueTypeFilter === 'resource' ? ' checked="checked"' : '' ?>><?= $translate('Resource') ?></label>
        <label><input type="radio" name="value_type" value="uri"<?= $valueTypeFilter === 'uri' ? ' checked="checked"' : '' ?>><?= $translate('Uri') ?></label>
        <label><input type="radio" name="value_type" value="resource_class"<?= $valueTypeFilter === 'resource_class' ? ' checked="checked"' : '' ?>><?= $translate('Resource class') ?></label>
        <label><input type="radio" name="value_type" value="resource_template"<?= $valueTypeFilter === 'resource_template' ? ' checked="checked"' : '' ?>><?= $translate('Resource template') ?></label>
        <label><input type="radio" name="value_type" value="owner"<?= $valueTypeFilter === 'owner' ? ' checked="checked"' : '' ?>><?= $translate('Owner') ?></label>
    </div>

    <div>
        <label><input type="radio" name="by_period" value="all"<?= $isByAll ? ' checked="checked"' : '' ?>><?= $translate('All') ?></label>
        <label><input type="radio" name="by_period" value="year"<?= $byPeriodFilter === 'year' ? ' checked="checked"' : '' ?>><?= $translate('By year') ?></label>
        <label><input type="radio" name="by_period" value="month"<?= $byPeriodFilter === 'month' ? ' checked="checked"' : '' ?>><?= $translate('By month') ?></label>
    </div>

    <select name="year">
        <option value=""><?= $translate('All years') ?></option>
        <?php foreach ($years as $year): ?>
            <option value="<?= $year ?>"<?= $yearFilter == $year ? ' selected="selected"' : '' ?>><?= $year ?></option>
        <?php endforeach; ?>
    </select>

    <?php $months = [
        1 => $translate('January'),
        2 => $translate('February'),
        3 => $translate('March'),
        4 => $translate('April'),
        5 => $translate('May'),
        6 => $translate('June'),
        7 => $translate('July'),
        8 => $translate('August'),
        9 => $translate('September'),
        10 => $translate('October'),
        11 => $translate('November'),
        12 => $translate('December'),
    ]; ?>
    <select name="month">
        <option value=""><?= $translate('All months') ?></option>
        <?php foreach ($months as $numberMonth => $month): ?>
            <option value="<?= $numberMonth ?>"<?= $monthFilter == $numberMonth ? ' selected="selected"' : '' ?>><?= $month ?></option>
        <?php endforeach; ?>
    </select>

    <div>
        <label><input type="radio" name="compute" value="count"<?= $isByCount ? ' checked="checked"' : '' ?>><?= $translate('Counts') ?></label>
        <label><input type="radio" name="compute" value="percent"<?= $compute === 'percent' ? ' checked="checked"' : '' ?>><?= $translate('Repartition') ?></label>
        <label><input type="radio" name="compute" value="evolution"<?= $compute === 'evolution' ? ' checked="checked"' : '' ?>><?= $translate('Evolution') ?></label>
        <label><input type="radio" name="compute" value="variation"<?= $compute === 'variation' ? ' checked="checked"' : '' ?>><?= $translate('Variation') ?></label>
    </div>

    <button type="submit"><?= $translate('Filter') ?></button>
</div>
</form>

<?php if (count($results) && ($propertyFilter || $isMetadata) && !is_null($periods)): ?>

<div class="browse-controls">
    <?php //= $this->pagination(); ?>
    <div>
        <?= $hyperlink($translate('ODS'), $this->url('admin/statistics/default/output', ['output' => 'ods'], ['query' => $query], true)) ?>
        <?= $hyperlink($translate('TSV'), $this->url('admin/statistics/default/output', ['output' => 'tsv'], ['query' => $query], true)) ?>
        <?= $hyperlink($translate('CSV'), $this->url('admin/statistics/default/output', ['output' => 'csv'], ['query' => $query], true)) ?>
    </div>
</div>

<?php endif; ?>

<?php if (!$propertyFilter && !$isMetadata): ?>

<p><?= $translate('Select a metadata to get statistics on it.') ?></p>

<?php elseif (is_null($periods)): ?>

<p><?= $translate('Check the form.') ?></p>

<?php elseif ($isAllPeriods && count($results)): ?>
<?php $period = 'all'; ?>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $currentUrl . '?sort_by=value' ?>"><?= $translate('Value') ?></a>
            </th>
            <?php if ($isLinked): ?>
            <th>
                <span><?= $translate('Label') ?></span>
            </th>
            <?php endif; ?>
            <?php foreach ($resourceTypes  as $resourceType): ?>
            <th>
                <span><?= $resourceType ?></span>
            </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <tr class="statistics-stat">
            <td class="statistics-field statistics-totals"><?= $translate('Totals') ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label statistics-totals"></td>
            <?php endif; ?>
            <?php foreach ($resourceTypes as $resourceType): ?>
            <td class="statistics-hits statistics-totals"><?= isset($totals[$period][$resourceType]) ? $totals[$period][$resourceType] : '' ?></td>
            <?php endforeach; ?>
        </tr>
<?php foreach ($results as $value => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $isUri ? '<a href="' . $escapeAttr($value) . '" target="_blank">' . $escape($result['l']) . '</a>' : $escape($value) ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label"><?= $escape($result['l']) ?></td>
            <?php endif; ?>
            <?php foreach ($resourceTypes as $resourceType): ?>
            <td class="statistics-hits"><?= isset($result['t'][$period][$resourceType]) ? $result['t'][$period][$resourceType] : '' ?></td>
            <?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php elseif (!$isAllPeriods && count($results)): ?>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $currentUrl . '?sort_by=value' ?>"><?= $translate('Value') ?></a>
            </th>
            <?php if ($isLinked): ?>
            <th>
                <span><?= $translate('Label') ?></span>
            </th>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <th>
                <span><?= $isYearPeriods ? $period : sprintf('%04d %02d', substr((string) $period, 0, 4), substr((string) $period, 4, 2)) ?></span>
            </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <tr class="statistics-stat">
            <td class="statistics-field statistics-totals"><?= $translate('Totals') ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label statistics-totals"></td>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <td class="statistics-hits statistics-totals"><?php
                // There may be missing resource types.
                $t = isset($totals[$period]) ? array_replace(array_fill_keys($resourceTypes, null), $totals[$period]) : array_fill_keys($resourceTypes, null);
                echo implode(' / ', $t);
            ?></td>
            <?php endforeach; ?>
        </tr>
<?php foreach ($results as $value => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $isUri ? '<a href="' . $escapeAttr($value) . '" target="_blank">' . $escape($result['l']) . '</a>' : $escape($value) ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label"><?= $escape($result['l']) ?></td>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <td class="statistics-hits"><?php
                // There may be missing resource types.
                $t = isset($result['t'][$period]) ? array_replace(array_fill_keys($resourceTypes, null), $result['t'][$period]) : array_fill_keys($resourceTypes, null);
                echo implode(' / ', $t);
            ?></td>
            <?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

    <br class="clear" />
    <?php $totalResources = $plugins->get('apiResourcesTotalResults')(); ?>
    <?php if (!$totalResources): ?>
        <h2><?= $translate('There is no resources yet.') ?></h2>
    <?php else: ?>
        <p><?= sprintf($translate('The query searched %s resources and returned no results.'), $totalResources) ?></p>
        <p><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-value'], true) ?>"><?= $translate('See all statistics.') ?></a></p>
    <?php endif; ?>

<?php endif; ?>
