<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

// Custom Verovio viewer.

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$assetUrl = $this->plugin('assetUrl');

$source = $options['source'] ?? $resource->originalUrl();

$this->headLink()
    ->appendStylesheet($assetUrl('css/verovio.css', 'Verovio'))
;
$this->headScript()
    ->appendFile($assetUrl('vendor/verovio/js/verovio-toolkit.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/verovio-toolkit.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
;
?>

<?php if (!empty($options['heading'])): ?>
    <h2><?= $options['heading'] ?></h2>
<?php endif; ?>

<div id="verovio" class="verovio" data-url="<?= $escape($source) ?>" <?= $options['attributes'] ?>>
    <?= $translate('The viewer is loading…') ?>
</div>
<noscript>
    <p>
        <?= $translate('This browser does not support javascript.') ?>
        <?= sprintf($translate('You may %sdownload it%s to view it offline.'), '<a href="' . $escape($source) . '">', '</a>') ?>
    </p>
</noscript>
