<?php
// アイコン表示用Element (ConfigFormで使用)
use Omeka\Api\Exception\NotFoundException;

$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/asset-form.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/asset-form.js', 'Omeka'));
// TODO アイコンファイル名をIDから取得する
$iconId = null;
$iconId = $element->getValue();
if ($iconId) 
{
    try
    {
        // IDからアイコンデータ取得
        $icon = $this->api()->read('iiif_viewers_icons', $iconId)->getContent();
    } 
    catch (NotFoundException $e)
    {
        $element->setValue(null);
    }
}
?>
<div class="asset-form-element<?php if (!$asset) echo ' empty'; ?>">
    <?php if ($icon):  // アイコンがあれば表示する ?>
    <span class="selected-asset" style="padding-left:20px;padding-top:10px;">
        <?php
        echo sprintf('<img class="selected-asset-image" src="%s" style="height:50px;"><div class="selected-asset-name" style="margin:0">%s</div>',
            $this->escapeHtml($icon->assetUrl()),
            $this->escapeHtml($icon->name())
        );
        ?>
    </span>
    <?php else: ?>
    <span class="selected-asset" style="display: none;">
        <img class="selected-asset-image"><div class="selected-asset-name"></div>
    </span>
    <?php endif; ?>
    <?php // 選択アイコンID設定用 ?>
    <?php echo $this->formHidden($element); ?>
</div>
