<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$urlHelper = $this->plugin('url');
?>
<div id="user-bar" >
<?php if ($user): ?>
	<div class="user-links">
	    <span class="user-id">
	        <?php
			/*
	        $url = $urlHelper('site/id', ['controller' => 'user', 'id' => $user->getId()]);
	        echo sprintf('%s', $hyperlink($user->getName(), $url));
			*/
	        echo $user->getName();
	        ?>
	    </span>
        <?php 
		//echo '<a href="'.$urlHelper('logout').'"><i class="fas fa-sign-out-alt"></i></a>';
		echo '<a href="'.$this->url('site', ['controller' => 'page', 'action' => 'logout'], true).'/page/logout"><i class="fas fa-sign-out-alt"></i></a>';
		
		?>
	</div>
<?php else: ?>
	<div class="user-links">
	<span class="user-id">Anonyme</span>
    <?php echo $hyperlink($translate('Log in'), $this->url('site', ['controller' => 'page', 'action' => 'logout'], true).'/page/presentation_projet', ['class' => 'login']); ?>
	</div>
<?php endif; ?>
</div>


