<div class="full-width">
<div class="banner">
	<?php
	$this->headLink()->appendStylesheet($this->assetUrl('css/banner.css', 'BannerImage'));		
	?>

	<div class="banner-image">
	<?php
		foreach ($urls as $url) {
			$html = sprintf('<div class="banner-wrap" style="%s"><img class="banner-img" style="%s" src="%s" alt="%s"></div>', $wrapStyle, $imgStyle, $url, $altText);
			echo $html;
		}
	?>
	</div>
	<div id="banner-overlay">
	<?php
		if ($title !== "") {
		$intro = sprintf('<p id="banner-title" style="%s">%s</p>', $textStyle, $title);
		echo $intro;
	}
	?>
	</div>

	<style>
		.banner-wrap { height: <?php echo $height ?>; }
		.banner-img { width: 100%; }
		#banner-overlay { background-image: <?php echo $ui_background ?>; }
	</style>
</div>
</div>