<?php
$mapping = $this->api()->searchOne('mappings', ['item_id' => $item->id()])->getContent();
$markers = $this->api()->search('mapping_markers', ['item_id' => $item->id()])->getContent();

if (!$mapping && !$markers) {
    return;
}

$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet/dist/leaflet.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.css', 'Mapping'));

$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet/dist/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet-providers/leaflet-providers.js', 'Mapping'));

$this->headScript()->appendFile($this->assetUrl('js/mapping-show.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
?>
<div id="mapping-section" class="section">
    <div id="mapping-map" style="height:500px;"
        data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"
    ></div>
</div>

<?php foreach ($markers as $marker): ?>
<?php
$item = $marker->item();
$media = $marker->media();
?>
<div class="mapping-marker-popup-content" style="display:none;"
    data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>"
    data-marker-lat="<?php echo $this->escapeHtml($marker->lat()); ?>"
    data-marker-lng="<?php echo $this->escapeHtml($marker->lng()); ?>"
>
    <?php if ($marker->label()): ?>
    <h3><?php echo $this->escapeHtml($marker->label()); ?></h3>
    <?php endif; ?>
    <?php if ($media): ?>
    <?php echo $this->thumbnail($media, 'medium'); ?>
    <div>
        <?php echo sprintf($this->translate('Media: %s'), $media->link($media->displayTitle())); ?>
    </div>
    <?php endif; ?>
    <div>
        <?php echo sprintf($this->translate('Item: %s'), $item->link($item->displayTitle())); ?>
    </div>
</div>
<?php endforeach; ?>
