<!-- BEGIN omeka/site/item/show.phtml -->

<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>

<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
              echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>

<?php 
// This call renders all the metadata.  It calls through to
// 'common/resource-values.phtml'.
echo $item->displayValues(); 
?>

<div class="property">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
    <h4><?php echo $translate('Item sets'); ?></h4>
    <?php foreach ($itemSets as $itemSet): ?>
    <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
    <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php if (!$embedMedia && $itemMedia): ?>

<div class="media-list">
<h3>Attached Media</h3>
    <?php foreach ($itemMedia as $media): ?>
        <?php 
          // Attached media gets shown using this call
          echo $media->linkPretty(); 
        ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>

<!-- END omeka/site/item/show.phtml -->
