<div>
<ul class="resource-list preview rdt-masonry-grid">
<?php foreach ($this->resources as $resource): ?>
    <li class="<?php echo $this->resourceType; ?> resource rdt-grid-item">
    <?php echo $resource->linkRaw($this->thumbnail($resource, 'medium', ['title' => $heading])); ?>
             <span><?= $resource->link($resource->displayTitle()); ?></span>
    </li>
<?php endforeach; ?>
</ul>
<!-- Masonry grid items use floats so they need to be cleared -->
<div class="rdt-clearleft"></div>
</div>
