<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var string $resourceName
 * @var string $resourceType
 * @var string $thumbnailType
 * @var array $options
 */

if (($thumbnailType === 'original' && !$media->hasOriginal())
    || ($thumbnailType !== 'original' && !$media->hasThumbnails())) return;

$alignmentClass = isset($options['align']) && in_array($options['align'], ['left', 'right', 'center'])
    ? $options['align']
    : '';
?>

<div class="shortcode <?= $alignmentClass . ' ' . $thumbnailType ?> file">
    <img src="<?= $thumbnailType === 'original' ? $media->originalUrl() : $media->thumbnailUrl($thumbnailType) ?>"/>
</div>
