<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $resourceName
 * @var string $resourceType
 * @var array $options
 */

// Adapted from view/common/block-layout/browse-preview

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');

if ($resource instanceof \Omeka\Api\Representation\AssetRepresentation) {
    $title = $resource->name();
    $description = $resource->thumbnailAltText();
} else {
    $title = $resource->displayTitle();
    $description = $resource->displayDescription();
}
?>

<div class="shortcode resource <?= $resourceType ?>">
    <?php if ($thumb = $thumbnail($resource, 'medium', ['title' => $title])): ?>
    <?= $resource->linkRaw($thumb) ?>
    <?php endif; ?>
    <h4><?= $resource->link($title) ?></h4>
    <?php if ($description): ?>
    <div class="description"><?= $escape($description) ?></div>
    <?php endif; ?>
</div>
