<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var string $resourceName
 * @var string $resourceType
 * @var array $options
 */

// Adapted from view/common/block-layout/browse-preview

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');
?>

<div class="shortcode resources <?= $resourceType ?>">
    <ul class="resource-list preview">
        <?php foreach ($resources as $resource):
        if ($resource instanceof \Omeka\Api\Representation\AssetRepresentation) {
            $title = $resource->name();
            $description = $resource->thumbnailAltText();
        } else {
            $title = $resource->displayTitle();
            $description = $resource->displayDescription();
        }
        ?>
        <li class="resource <?= $resourceType?>">
            <?php $thumb = $thumbnail($resource, 'medium', ['title' => $title]); ?>
            <?= $resource->linkRaw($thumb) ?>
            <h4><?= $resource->link($title) ?></h4>
            <?php if ($description): ?>
            <div class="description"><?= $escape($description) ?></div>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
