<?php
$json = $this->params()->fromQuery('json') ? $this->params()->fromQuery('json') : $this->params()->fromPost('json', '');
if($json){
    echo $this->content;
    return ;
}

$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')
    ->setAttribute('lang', $this->lang())
    ->setAttribute('class', "h-100");
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));

$this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/cover.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->appendFile($this->assetUrl('js/jquery-3.4.1.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/bootstrap.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/all.min.js'));//fontawesome
$this->headScript()->appendFile($this->assetUrl('js/d3.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/geoLoc.js'));
$this->headScript()->appendFile($this->assetUrl('js/jBox.all.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/modalPatienter.js'));
$this->headScript()->appendFile($this->assetUrl('js/main.js'));
$this->headScript()->appendFile($this->assetUrl('js/tableQuestions.js'));
$this->headScript()->appendFile($this->assetUrl('js/polarclock.js'));
$this->headScript()->appendFile($this->assetUrl('js/cartoaxes.js'));
$this->headScript()->appendFile($this->assetUrl('js/avancementProcess.js'));


$this->trigger('view.layout');

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
                
    </head>

    <body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    <!--- begin header----->
    <?php echo $this->partial('FeuNum/header'); ?>
    <!--- end header------->
    <!--- begin menu----->
    <?php echo $this->partial('FeuNum/menu'); ?>
    <!--- end menu------->

    
      <main class="pt-3 px-3 mb-3 border border-5 border-top-0 border-light text-start " >
        <?php echo $this->content; ?>
      </main>
    
      <?php echo $this->partial('FeuNum/footer'); ?>

    </div>
    
    
        
      </body>
</html>