<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $results
 * @var array $totals
 * @var string $type "value"
 * @var string[] $resourceTypes
 * @var int[]|null $periods
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 * @var string $propertyFilter
 * @var string $valueTypeFilter
 * @var string $byPeriodFilter
 * @var string $compute
 * @var bool $hasAdvancedSearch
 */

include __DIR__ . '/../../site/statistics/by-value.phtml';
