<?php
if($page->slug()=='logout'){
    echo $this->partial('FeuNum/'.$page->slug(), []);
    return;
}
if($page->slug()=='ajax'){
    echo $this->partial('FeuNum/'.$page->slug(), []);
    return;
}
if($page->slug()=='repondre-enquete'){
    //vérifie si l'utilisateur à répondu au questionnaire de profil
    $profil = $this->api()->search('items', ['item_set_id' => 666,'owner_id'=>$this->identity()->getId()])->getContent();
    if(count($profil)==0){
        header("Location: profil");
        exit;    
    }
    $this->getQuestionsProcess();
}
if($page->slug()=='repondre-question'){
    $id = $this->params()->fromQuery('id',false);
    if($id){
        $crible = $this->api()->read('items',$id)->getContent();
        $this->getCrible($crible);
        $this->getQuestionNavig($crible);    
        $this->getQuestionsProcess();
    }
}

$this->headLink()->appendStylesheet($this->assetUrl('css/page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
