<?php
// アイコン設定用Element
use Omeka\Api\Exception\NotFoundException;

$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/asset-form.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/asset-form.js', 'IiifViewers'));
// ElementからID取得
$icon = null;
$iconId = $element->getValue();
if ($iconId)
{
    try 
    {
        // IDからアイコンデータ取得
        $icon = $this->api()->read('iiif_viewers_icons', $iconId)->getContent();
    }
    catch (NotFoundException $e) {
        $element->setValue(null);
    }
}
?>
<div class="asset-form-element<?php if (!$icon) echo ' empty'; ?>">
    <?php if ($icon): // アイコンがあれば表示する ?>
    <span class="selected-asset">
        <?php
        echo sprintf('<img class="selected-asset-image" src="%s" style="height:75px;"><div class="selected-asset-name">%s</div>',
            $this->escapeHtml($icon->assetUrl()),
            $this->escapeHtml($icon->name())
        );
        ?>
    </span>
    <?php else: ?>
    <span class="selected-asset" style="display: none;">
        <img class="selected-asset-image"><div class="selected-asset-name"></div>
    </span>
    <?php endif; ?>
    <span class="no-selected-asset">
        <?php echo $translate('[No Icon selected]'); ?>
    </span>
    <?php // 選択ボタン ?>
    <button type="button" class="asset-form-select" data-sidebar-content-url="<?php echo $this->escapeHtml($this->url('admin/default', ['controller' => 'iiif-viewers', 'action' => 'sidebar-select'])); ?>">
        <?php echo $translate('Select'); ?>
    </button>
    <?php // クリアボタン ?>
    <button type="button" class="asset-form-clear red button">
        <?php echo $translate('Clear'); ?>
    </button>
    <?php // 選択アイコンID設定用 ?>
    <?php echo $this->formHidden($element); ?>
</div>
