<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Statistics\Api\Representation\StatRepresentation[] $stats
 * @var string $userStatus
 * @var string $type
 *
 * @todo Add the basePath to the hit url.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$isAdminRequest = $this->status()->isAdminRequest();

$totalResults = $this->pagination()->getPaginator()->getTotalCount();
$currentUrl = $urlHelper(null, [], true);
$basePath = $this->basePath();
?>

<?= $this->pageTitle(sprintf($translate('Analytics (%s total)'), $totalResults), 1, $isAdminRequest ? $translate('Analytics') : null) ?>

<?= $this->partial('common/analytics-nav') ?>

<?php if ($stats): ?>

<div class="browse-controls">
    <?= $pagination = $this->pagination() ?>
    <?php //= $this->hyperlink($translate('Advanced search'), $urlHelper(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']) ?>
    <?= $this->partial('common/analytics-quick-filters') ?>
    <?php //= $this->sortSelector($sortHeadings) ?>
</div>
<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $currentUrl . '?sort_by=url' ?>"><?= $translate('Page') ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=hits' ?>"><?= $translate('Hits') ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=anonymous' ?>"><?= $translate('Anonymous') ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=identified' ?>"><?= $translate('Identified') ?></a>
            </th>
            <th>
                <span><?= $translate('Dedicated resource') ?></span>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=resource_type' ?>"><?= $translate('Resource type') ?></a>
            </th>
            <th>
                <a href="<?= $currentUrl . '?sort_by=modified' ?>"><?= $translate('Date') ?></a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($stats as $stat): ?>
        <tr class="statistics-stat">
            <td class="statistics-url">
                <div class="statistics-hover">
                    <a href="<?= $escapeAttr($basePath . $stat->hitUrl()) ?>"><?= $escape($stat->hitUrl()) ?></a>
                </div>
            </td>
            <td class="statistics-hits">
                <?= $stat->totalHits() ?>
            </td>
            <td class="statistics-hits stats-anonymous">
                <?= $stat->totalHits('anonymous') ?>
            </td>
            <td class="statistics-hits stats-identified">
                <?= $stat->totalHits('identified') ?>
            </td>
            <td class="statistics-resource">
                <?php if ($stat->hasResource()): ?>
                <div class="statistics-hover">
                    <?= $stat->linkEntity() ?>
                </div>
                <?php endif; ?>
            </td>
            <td class="statistics-record-type">
                <?php if ($stat->hasResource()): ?>
                    <?= $stat->humanResourceType() ?>
                <?php endif; ?>
            </td>
            <td>
                <?= $escape($stat->modified()->format('Y-m-j H:i:s')) ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
    <?= $pagination ?>

<?php else: ?>

<div class="browse-controls">
    <?= $this->partial('common/analytics-quick-filters') ?>
</div>
<?php $totalStats = $this->api()->search('stats', ['limit' => 0])->getTotalResults(); ?>
<div class="no-resources">
<?php if (!$totalStats): ?>
    <p><?= $translate('Omeka could not find any statistics.') ?></p>
<?php else: ?>
    <p><?= sprintf($translate('The query searched %s rows and returned no results.'), $totalStats) ?></p>
    <p><a href="<?= $urlHelper('admin/analytics/default', ['action' => 'by-' . $type], true) ?>"><?= $translate('See all analytics.') ?></a></p>
<?php endif; ?>
</div>

<?php endif; ?>
